spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/2tdspf-authentication?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: true
      show-sql: true
      generate-ddl: true
